version: "3"
services:
  postgres:
    image: postgres
    container_name: bookshelf
    ports:
      - "6500:5432"
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
